version: "3.7"

services:
  snekbox:
    container_name: snekbox_dev
    hostname: snekbox_dev
    privileged: true
    image: ghcr.io/onerandomusername/snekbox${IMAGE_SUFFIX:--venv:dev}
    pull_policy: never
    ports:
     - "8060:8060"
    init: true
    ipc: private
    tty: true
    environment:
      SNEKBOX_DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
    build:
      context: .
      dockerfile: Dockerfile
      target: venv
      args:
        DEV: 1
      cache_from:
        - ghcr.io/onerandomusername/snekbox:latest
    volumes:
      - .:/snekbox
      - user-base:/snekbox/user_base

volumes:
  user-base:
